export const ImagesActionTypes = {
  ADD_IMAGE: 'ADD_IMAGE',
  DELETE_IMAGE: 'DELETE_IMAGE',
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  SET_DELETE_ID: 'SET_DELETE_ID',
  SEARCH_CHANGE: 'SEARCH_CHANGE',

  FETCH_IMAGES_START: 'FETCH_IMAGES_START',
  FETCH_IMAGES_SUCCESS: 'FETCH_IMAGES_SUCCESS',
  FETCH_IMAGES_FAILURE: 'FETCH_IMAGES_FAILURE',
};
