export const ImagesActionTypes = {
  ADD_IMAGE: 'ADD_IMAGE',
  DELETE_IMAGE: 'DELETE_IMAGE',
  SET_CURRENT: 'SET_CURRENT',
  CLEAR_CURRENT: 'CLEAR_CURRENT',
  FILTER_IMAGES: 'FILTER_IMAGES',
  CLEAR_FILTER: 'CLEAR_FILTER',
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  SET_DELETE_ID: 'SET_DELETE_ID',
};
